CREATE TABLE TB_USERS (
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE TB_PRODUCTS (
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    BRAND VARCHAR(25) NOT NULL, 
    PRICE MONEY NOT NULL,
    DISCOUNT MONEY,
    CHECK (DISCOUNT < PRICE),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (ID)
); 

CREATE TABLE TB_PRODUCT_VARIANT (
    ID UUID NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    PRODUCT_ID UUID NOT NULL REFERENCES TB_PRODUCTS(ID),
    COLOR_PRIM VARCHAR(7) NOT NULL,
    COLOR_SEC VARCHAR(7) NOT NULL,
    IMAGE_URL VARCHAR(300) NOT NULL
);

CREATE TABLE TB_SIZES ( 
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    SIZE_US DECIMAL(3, 1) NOT NULL,
    SIZE_PE DECIMAL(3, 1) NOT NULL,
    SIZE_UK DECIMAL(3, 1) NOT NULL,
    SIZE_EU DECIMAL(3, 1) NOT NULL,
    SIZE_CM DECIMAL(3, 1) NOT NULL, 
    PRIMARY KEY (ID)
);

CREATE TABLE TB_STOCK (
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    VARIANT_ID UUID NOT NULL REFERENCES TB_PRODUCT_VARIANT(ID),
    SIZE_ID UUID NOT NULL REFERENCES TB_SIZES(ID),
    QUANTITY INT NOT NULL CHECK (QUANTITY >= 0),
    PRIMARY KEY (ID)
);

CREATE TABLE TB_ORDERS (
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    USER_ID UUID NOT NULL REFERENCES TB_USERS(ID),
    TOTAL MONEY NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE TB_ORDER_ITEMS (
    ORDER_ID UUID NOT NULL REFERENCES TB_ORDERS(ID),
    VARIANT_ID UUID NOT NULL REFERENCES TB_PRODUCT_VARIANT(ID),
    SIZE_ID UUID NOT NULL REFERENCES TB_SIZES(ID),
    QUANTITY INT NOT NULL CHECK (QUANTITY >= 0)
);

CREATE TABLE TB_REVIEWS (
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    USER_ID UUID NOT NULL REFERENCES TB_USERS(ID),
    PRODUCT_ID UUID NOT NULL REFERENCES TB_PRODUCTS(ID),
    RATING INT NOT NULL CHECK (RATING >= 0 AND RATING <= 10),
    COMMENT VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TB_FAVORITES (
    USER_ID UUID NOT NULL REFERENCES TB_USERS(ID),
    VARIANT_ID UUID NOT NULL REFERENCES TB_PRODUCT_VARIANT(ID),
    PRIMARY KEY (USER_ID, VARIANT_ID)
);

CREATE TABLE TB_CART_ITEMS (
    USER_ID UUID NOT NULL REFERENCES TB_USERS(ID),
    VARIANT_ID UUID NOT NULL REFERENCES TB_PRODUCT_VARIANT(ID),
    SIZE_ID UUID NOT NULL REFERENCES TB_SIZES(ID),
    QUANTITY INT NOT NULL CHECK (QUANTITY >= 0),
    PRIMARY KEY (USER_ID, VARIANT_ID, SIZE_ID)
);

```
DROP TABLE TB_CART_ITEMS;
DROP TABLE TB_FAVORITES;
DROP TABLE TB_REVIEWS;
DROP TABLE TB_ORDER_ITEMS;
DROP TABLE TB_ORDERS;
DROP TABLE TB_STOCK;
DROP TABLE TB_SIZES;
DROP TABLE TB_PRODUCT_VARIANT;
DROP TABLE TB_PRODUCTS;
DROP TABLE TB_USERS;
```
